version: '3.8'

name: rabbitmq4-dotnet-example

volumes:
  rabbitmq_data:
    driver: local

services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: .
      dockerfile: Dockerfiles/RabbitMq/Dockerfile
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: 00PQp6P8iD0HtTpGQ98kS04rU3Fkd2
    ports:
      - "5672:5672"    # RabbitMQ bağlantı portu
      - "15672:15672"  # RabbitMQ yönetim paneli portu
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  publisher:
    image: publisher
    container_name: publisher
    build:
      context: .
      dockerfile: Publisher/Dockerfile
    restart: always
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
    environment:
      - "Settings:RabbitMq:Host=rabbitmq"
      - "Settings:RabbitMq:Port=5672"
      - "Settings:RabbitMq:Username=rabbitmq"
      - "Settings:RabbitMq:Password=00PQp6P8iD0HtTpGQ98kS04rU3Fkd2"

  consumer:
    image: consumer
    container_name: consumer
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    restart: always
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq
    environment:
      - "Settings:RabbitMq:Host=rabbitmq"
      - "Settings:RabbitMq:Port=5672"
      - "Settings:RabbitMq:Username=rabbitmq"
      - "Settings:RabbitMq:Password=00PQp6P8iD0HtTpGQ98kS04rU3Fkd2"