version: '3.8'

volumes:
  rabbitmq_data:
    driver: local

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: 00PQp6P8iD0HtTpGQ98kS04rU3Fkd2
    ports:
      - "5672:5672"    # RabbitMQ bağlantı portu
      - "15672:15672"  # RabbitMQ yönetim paneli portu
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    # Command for delayed message and message duplication control
#    command: >
#      sh -c "
#      rabbitmq-plugins enable rabbitmq_message_deduplication &&
#      rabbitmq-plugins enable rabbitmq_delayed_message_exchange
#      "

#  publisher:
#    image: publisher
#    container_name: publisher
#    build:
#      context: .
#      dockerfile: Publisher/Dockerfile
#    restart: always
#    ports:
#      - "5001:80"
#    depends_on:
#      - rabbitmq
#
#  consumer:
#    image: consumer
#    container_name: consumer
#    build:
#      context: .
#      dockerfile: Consumer/Dockerfile
#    restart: always
#    ports:
#      - "5002:80"
#    depends_on:
#      - rabbitmq